version: '2'
services:
  nginx:
    build: .
    env_file: .env
    environment:
      SERVICE_NAME: router
    ports:
      - 80:80
    links:
      - consul
    restart: on-failure:10
  
  consul:
    image: consul
    env_file: .env
    command: agent -server -ui -client 0.0.0.0 -bootstrap-expect=1
    restart: on-failure:10
    ports:
      - "8500:8500"
    volumes:
      - ./docker-volumes/consul/data:/data
